@domain=http://127.0.0.1:8000

###
GET {{domain}}/

###
GET {{domain}}/api/collections

###
GET {{domain}}/api/questions

### Generate SQL
POST {{domain}}/api/generate-sql
Content-Type: application/json

{
    "question": "what are the top 5 accounts with most activities?"
}

### Run SQL Query
POST {{domain}}/api/run-sql
Content-Type: application/json

{
    "sql": "select aa.account_id, aa.account_name, count(aa.activity_id) as total_activities\nfrom analytics.silver_fact.crowd_dev_activities aa\ngroup by aa.account_id, aa.account_name\norder by total_activities desc\nlimit 5;"
}

### Get Training Data
GET {{domain}}/api/training-data

### Remove All Training Data
DELETE {{domain}}/api/remove-all-training-data


### 
### Add Training Data
POST {{domain}}/api/ingest-training-data-from-file
Content-Type: application/json

### 
